packages:
  - packages/*

ignoredBuiltDependencies:
  - esbuild

catalogs:
  frontend:
    "@fontsource-variable/montserrat": "^5.2.6"
    "@janis.me/react-themed": ^0.2.1
    "@janis.me/ui": "0.1.2-alpha.3"
    clsx: ^2.1.1
    include-media: ^2.0.0
    react-dom: ^19.1.0
    react: ^19.1.0
    sanitize.css: ^13.0.0
    zustand: ^5.0.5
    comlink: ^4.4.2
  build:
    "@vitejs/plugin-react": ^4.6.0
    sass: ^1.89.2
    typescript: ^5.8.3
    vite: ^6.3.5
    "vite-plugin-wasm": "^3.4.1"
  format:
    "@ianvs/prettier-plugin-sort-imports": ^4.4.2
    prettier-plugin-packagejson: ^2.5.15
    prettier: ^3.6.1
  lint:
    "@eslint/eslintrc": ^3.3.1
    "@eslint/js": ^9.29.0
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react: ^7.37.5
    eslint: ^9.29.0
    jiti: ^2.4.2
    typescript-eslint: ^8.35.0
  test:
    "@playwright/test": ^1.53.1
    "@vitest/browser": ^3.2.4
    vitest: ^3.2.4
  types:
    "@types/node": ^22.15.33
    "@types/react-dom": ^19.1.6
    "@types/react": ^19.1.8
  script:
    taze: ^19.1.0
