[package]
name = "calc"
version = "0.1.0"
authors = ["Janis Jansen <oss@janis.me>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
neal = { path = "../../../neal/neal" }
wasm-bindgen = "0.2.84"
console_error_panic_hook = { version = "0.1.7", optional = true }
web-sys = { version = "0.3", features = [
  "Document",
  "Element",
  "HtmlElement",
  "Node",
  "Window",
] }
js-sys = "0.3.77"
chrono = "0.4.11"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O2"]

[features]
default = ["console_error_panic_hook"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true
